const Endpoint = {
  LOGIN: "api/v1/auth/login/post/",
  SIGN_UP: "/dev/api/v1/auth/sign_up/post/",
  SIGN_OUT: "api/v1/auth/signout/post/",
  CHANGE_PASSWORD: "api/v1/auth/change_password/post/",
  FORGOT_PASSWORD: "/dev/api/v1/auth/forgot_password/post/",
  CONFIRM_FORGOT_PASSWORD: "/dev/api/v1/auth/confirm_forgot_password/post/",
  VERIFY_OTP: "/dev/api/v1/auth/verify_otp/post/",
  RESEND_OTP: "/dev/api/v1/auth/resend_otp/post/",
  VERIFY_MFA: "api/v1/auth/mfa_verify/post/",
  IS_MFA: "api/v1/auth/is_mfa/post/",
  GET_SOFTWARE_TOKEN: "api/v1/auth/associate_software_token/post/",
  VERIFY_SOFTWARE_TOKEN: "api/v1/auth/verify_access_token/post/",
  SET_MFA_PREFERENCE: "api/v1/auth/verify_software_token/post/",
  SET_MFA_PREFERENCE_UPDATE: "api/v1/auth/set_mfa_preference/post/",
  UAM: {
    KEYWORD_OVERVIEW: "/api/v1/ecom/unified_ad_manager/keyword_overview/post/",
    KEYWORD_UPDATE: "/api/v1/ecom/unified_ad_manager/keyword_update/post/",
    AD_GROUP_OVERVIEW:
      "/api/v1/ecom/unified_ad_manager/ad_group_overview/post/",
    ADD_KEYWORD: "/api/v1/ecom/unified_ad_manager/add_keyword/post/",
    CAMPAIGN_OVERVIEW_POST:
      "/api/v1/ecom/unified_ad_manager/campaign_update/post/",
    CAMPAIGN_OVERVIEW:
      "/api/v1/ecom/unified_ad_manager/campaign_overview/post/",
    PRODUCT_OVERVIEW: "/api/v1/ecom/unified_ad_manager/product_overview/post/",
    PRODUCT_OVERVIEW_UPDATE:
      "/api/v1/ecom/unified_ad_manager/product_update/post/",
    AD_GROUP_UPDATE: "/api/v1/ecom/unified_ad_manager/ad_group_update/post/",
    CREATE_CAMPAIGN: "/api/v1/ecom/unified_ad_manager/campaign_create/post/",
    PLATFORM_FILTER: "/api/v1/ecom/unified_ad_manager/filters/platform/post/",
    STATUS_FILTER: "/api/v1/ecom/unified_ad_manager/filters/status/post/",
    CAMPAIGN_TYPE_FILTER:
      "/api/v1/ecom/unified_ad_manager/filters/campaign_type/post/",
    CAMPAIGN_NAME_FILTER:
      "/api/v1/ecom/unified_ad_manager/filters/campaign_name/post/",
    AD_GROUP_NAME_FILTER:
      "/api/v1/ecom/unified_ad_manager/filters/ad_group_name/post/",
    KEYWORD_FILTER: "/api/v1/ecom/unified_ad_manager/filters/keyword/post/",
    MATCH_TYPE_FILTER: "/api/v1/ecom/unified_ad_manager/filters/keyword/post/",
    PRODUCT_CODE_FILTER:
      "/api/v1/ecom/unified_ad_manager/filters/product_code/post/",
    AD_KEYWORD: "/api/v1/ecom/unified_ad_manager/add_keyword/post/",
    AD_PRODUCT: "/api/v1/ecom/unified_ad_manager/add_product/post/",
    // LOGS
    CAMPAIGN_LOGS: "/api/v1/ecom/unified_ad_manager/campaign_logs/post/",
    AD_GROUP_LOGS: "/api/v1/ecom/unified_ad_manager/ad_group_logs/post/",
    KEYWORD_LOGS: "/api/v1/ecom/unified_ad_manager/keyword_logs/post/",
    PRODUCT_LOGS: "/api/v1/ecom/unified_ad_manager/product_logs/post/",
    RULE_LOGS: "/api/v1/ecom/unified_ad_manager/rule_engine_logs/post/",
    RULE_RESPONSE: "/api/v1/ecom/unified_ad_manager/rule_engine_api_response/get/ge",
  },
  RULES: {
    GET_RULES_RULESET: "/getRules_RuleSet",
    FILTERS_RULES_RULESET: "/filterRules_RuleSet",
  },


  

  PRODUCT:"access_control/products",
TRAFFIC_COUNT : "dev/api/v1/web/performance/traffic_counts",
EVENT_TRAFFIC : "dev/api/v1/web/performance/event_traffic",
VISIT_TRAFFIC : "dev/api/v1/web/performance/visit_traffic",
TOP_CAMPAIGNS : "dev/api/v1/web/performance/top_campaigns",
TOP_PUBLISHERS : "dev/api/v1/web/performance/top_publishers",
VISIT_TRAFFIC_PUBLISHER :"dev/api/v1/web/performance/visit_traffic_publisher",
EVENT_TRAFFIC_PUBLISHER :"dev/api/v1/web/performance/event_traffic_publisher",
TRAFFIC_TRENDS : "dev/api/v1/web/performance/traffic_trends",
COLOR_API :"dev/api/v1/web/performance/colors"       ,       
SUB_PUBLISHERS: "dev/api/v1/web/performance/filters/sub_publishers",
CAMPAIGNS: "dev/api/v1/web/performance/filters/campaigns",
CHANNELS: "dev/api/v1/web/performance/filters/channels",
PUBLISHERS: "dev/api/v1/web/performance/filters/publishers",
REPEAT_USERS_TABLE: "dev/api/v1/web/performance/repeat_users_table",
BOT_BEHAVIOUR :"dev/api/v1/web/performance/bot_behaviour",
REPEAT_IP :"dev/api/v1/web/performance/repeat_ip",
HARDWARE_CONCURRENCY :"dev/api/v1/web/performance/hardware_concurrency",
INVALID_GEO :"dev/api/v1/web/performance/invalid_geo",
IFRAME_SIZE :"dev/api/v1/web/performance/iframe_size",
POP_UNDER :"dev/api/v1/web/performance/pop_under",
VPN_PROXIES :"dev/api/v1/web/performance/vpn_proxies",
TRAFFIC_CONTRIBUTION :"dev/api/v1/web/performance/traffic_contribution",
TOP_CONTRIBUTING_OS_VERSIONS:"dev/api/v1/web/performance/top_contributing_os_versions",
STATE_VISIT:"dev/api/v1/web/performance/state_visit",
STATE_EVENT:"dev/api/v1/web/performance/state_event",
GOOGLE:"dev/api/v1/web/performance/google",
META:"dev/api/v1/web/performance/meta",
BLOCKED_REPORT_GOOGLE:"dev/api/v1/web/performance/blocked_report_google",
BLOCKED_REPORT_META:"dev/api/v1/web/performance/blocked_report_meta",
OVERALL_PLACEMENT:"dev/api/v1/web/performance/overall_placements",
OVERALL_PLACEMENT_TABLE:"dev/api/v1/web/performance/overall_placements_table",
UNSAFE_PLACEMENT:"dev/api/v1/web/performance/unsafe_placements",
UNSAFE_PLACEMENT_TABLE:"dev/api/v1/web/performance/unsafe_placements_table",
USER_INTENT:"dev/api/v1/web/performance/user_intent",
AUDIENCE_OPTIMIZATION_FACEBOOK:"dev/api/v1/web/performance/audience_optimization_facebook",
OPTIMIZATION_FACEBOOK_TABLE:"dev/api/v1/web/performance/audience_optimization_facebook_table",
AUDIENCE_OPTIMIZATION_GOOGLE_TABLE:"dev/api/v1/web/performance/audience_optimization_google_table",
DEVICE_CONCENTRATION:"dev/api/v1/web/performance/device_concentration",
AUDIENCE_OPTIMIZATION_GOOGLE:"dev/api/v1/web/performance/audience_optimization_google",
EVENT_TYPE:"dev/api/v1/web/performance/filters/event_type",
REDIS_GET_API:"dev/api/v1/web/performance/redis_get_api",
REDIS_API:"dev/api/v1/web/performance/redis_api",
GOOGLE_ADS_LOGIN:"/api/v1/web/performance/google_ads_login",
GOOGLE_ADS_AUTH_API:"/api/v1/web/performance/google_ads_token_fetch",
COUNTRY:"dev/api/v1/web/performance/filters/country",
LIST_USER:"dev/api/v1/auth/list_users",
USER_INFORMATION:"access_control/getUser",
// PRODUCT:"access_control/products",
ROLE_LIST:"access_control/rolesList",
PACKAGE:"access_control/packages",
CREATE_PACKAGE:"access_control/createPackage",
REPORT_CATEGORY:"common/reporting_tool/get_category",
REPORT_TEMPLATE:"common/reporting_tool/get_templates",
REPORT_TEMPLATE_FIELDS:"common/reporting_tool/get_template_fields",
REPORT_CUSTOM_TEMPLATE:"common/reporting_tool/custome_template",
REPORT_GET_API :"common/reporting_tool/get_all_reports",
REPORT_FILTERS:"common/reporting_tool/filters",
MAILING_LIST_GET_API:"common/reporting_tool/list_all_mailing_lists",
CREATE_MAILING_LIST_API:"common/reporting_tool/create_mailing_list",
UPDATE_MAILING_LIST_API:"common/reporting_tool/edit_mailing_list",
REPORT_CREATE_API:"common/reporting_tool/create_report",
REPORT_THRESHOLD_API:"common/reporting_tool/threshold",
REPORT_DELETE_API:"common/reporting_tool/delete_report",
REPORT_CLONE_API:"common/reporting_tool/copy_report",
VIEW_REPORT_API:"common/reporting_tool/view_report",
REPORT_EDIT_API:"common/reporting_tool/edit_report",
REPORT_STATUS_UPDATE_API:"common/reporting_tool/update_status",
REPORT_STATUS_MAIL_UPDATE_API:"common/reporting_tool/status_change_mailing_list",
GET_MENU_API:"access_control/menus",
USER_LIST:"access_control/userList",
ADD_USER:"access_control/addToUser",
PACKAGE_MAPPING:"access_control/packageMapping",
EDIT_USERROLES: "access_control/editUserRoles",
CREATE_USER:"access_control/createUser",
DELETE_PACKAGE:"access_control/deletePackage",
DELETE_PRODUCTUSER:"access_control/deleteRolesFromUser",
DELETE_USER :"access_control/deleteUser",
EDIT_USER:"access_control/editUser",
EDIT_PACKAGE:"access_control/editPackage",
CALL_RECOMMENDATION_GET:"dev/api/v1/web/performance/get_call_recommendation",
CALL_RECOMMENDATION_STATUS_UPDATE:"dev/api/v1/web/performance/call_recommendation_status_update",
CALL_RECOMMENDATION_UPDATE :"dev/api/v1/web/performance/call_recommendation_update",
GET_REAL_TIME_TABLE :"dev/api/v1/web/performance/get_real_time",
TOGGLE_CHANNEL_STATUS:"dev/api/v1/web/performance/toggle_channel_status",
TOGGLE_ACTION_STATUS:"dev/api/v1/web/performance/toggle_action_status",
}


export const RULE_ENGINE_URL =
  process.env.NEXT_PUBLIC_RULE_ENGINE_URL || "https://ruleengine.mfilterit.net";

export default Endpoint;
